require('aditya.plugins-setup')

require('aditya.core.options')
require('aditya.core.colorscheme')
require('aditya.core.keymaps')

require('aditya.plugins.comment')
require('aditya.plugins.nvim-surround')
require('aditya.plugins.nvim-tree')
require('aditya.plugins.lualine')
require('aditya.plugins.telescope')
require('aditya.plugins.nvim-cmp')
require('aditya.plugins.lsp.mason')
require('aditya.plugins.lsp.lspsaga')
require('aditya.plugins.lsp.lspconfig')
require('aditya.plugins.lsp.null-ls')
require('aditya.plugins.dashboard')
require('aditya.plugins.autopairs')
require('aditya.plugins.treesitter')
require('aditya.plugins.gitsigns')

